name: Deploy npm library
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile --ignore-scripts

    - name: Build
      run: yarn build

    - name: Publish to npm
      run: |
        yarn publish --access public --non-interactive --no-progress --registry https://registry.npmjs.org/ --tolerate-republish --new-version ${{ github.ref_name }}

      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}