name: Deploy npm library
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile --ignore-scripts

    - name: Build
      run: yarn build

    - name: Publish to npm
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" | yarn config set registry $(yarn config get registry)
        npm publish --access public --non-interactive --no-progress
